# fly.toml app configuration file generated for pred-inktmg on 2026-06-13T01:52:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pred-inktmg'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/pred.db'
  PORT = '3000'

[[mounts]]
  source = 'pred_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
